name: acrilico
description: "Demonstração de efeito de vidro/acrílico."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.4 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true
  assets: # Images from www.pexels.com
    - img/noise.png
    - img/forest.jpg
    - img/cold.jpg
    - img/trees.jpg
    - img/fall.jpg
    - img/triangles.jpg
    - img/clouds.jpg
    - img/bubbles.png # taken from a figma file
    - img/google.svg
